@url = http://localhost:3333

### Create a ONG
POST  {{url}}/ongs
Content-Type: application/json

{
    "name": "Be a Hero",
    "email": "behero@hero",
    "whatsapp": "+5589989898989",
    "city": "Picos",
    "uf": "PIs"
}

### List ONG
GET  {{url}}/ongs
